# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmap', '0006_remove_unnecessary_index_20160130_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksearchhistory',
            name='last_manual_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
