# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rphistory', '0004_song_corrected_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
