# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rphistory', '0005_song_isrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
